learn_alignment: true
n_speakers: 1
symbols_embedding_dim: 384
max_token_duration: 75
n_mel_channels: 80
pitch_embedding_kernel_size: 3
n_window_size: 1024
n_window_stride: 256
pitch_fmin: 80
pitch_fmax: 640
pitch_avg: 211.27540199742586
pitch_std: 52.1851002822779

phoneme_dict_path: "scripts/tts_dataset_files/cmudict-0.7b_nv22.01"
heteronyms_path: "scripts/tts_dataset_files/heteronyms-030921"
whitelist_path: "nemo_text_processing/text_normalization/en/data/whitelist_lj_speech.tsv"

text_normalizer:
    _target_: nemo_text_processing.text_normalization.normalize.Normalizer
    lang: en
    input_case: cased
    whitelist: ${whitelist_path}

text_normalizer_call_kwargs:
  verbose: false
  punct_pre_process: true
  punct_post_process: true

text_tokenizer:
  _target_: nemo.collections.tts.torch.tts_tokenizers.EnglishPhonemesTokenizer
  punct: true
  stresses: true
  chars: true
  apostrophe: true
  pad_with_space: true
  add_blank_at: true
  g2p:
    _target_: nemo.collections.tts.torch.g2ps.EnglishG2p
    phoneme_dict: ${phoneme_dict_path}
    heteronyms: ${heteronyms_path}
    phoneme_probability: 0.5

train_ds:
  dataset:
    _target_: nemo.collections.tts.torch.data.TTSDataset
    manifest_filepath: /raid/LJSpeech/nvidia_ljspeech_train.json
    max_duration: null
    min_duration: 0.1
    sample_rate: 22050
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    window: hann
    trim: false
    n_mels: 80
    lowfreq: 0
    highfreq: 8000
    sup_data_types:
    sup_data_path: /raid/LJSpeech/prior
    pitch_fmin: 80
    pitch_fmax: 640
    pitch_avg: 211.27540199742586
    pitch_std: 52.1851002822779
    use_beta_binomial_interpolator: true
  dataloader_params:
    drop_last: false
    shuffle: true
    batch_size: 32
    num_workers: 12
validation_ds:
  dataset:
    _target_: nemo.collections.tts.torch.data.TTSDataset
    manifest_filepath: /raid/LJSpeech/nvidia_ljspeech_val.json
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    window: hann
    n_mels: 80
    lowfreq: 0
    highfreq: 8000
    max_duration: null
    min_duration: null
    ignore_file: null
    sample_rate: 22050
    trim: false
    sup_data_types:
    sup_data_path: /raid/LJSpeech/prior
    pitch_fmin: 80
    pitch_fmax: 640
    pitch_norm: true
    pitch_mean: 211.27540199742586
    pitch_std: 52.1851002822779
    use_beta_binomial_interpolator: true
  dataloader_params:
    drop_last: false
    shuffle: false
    batch_size: 32
    num_workers: 8
preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  dither: 0.0
  features: 80
  frame_splicing: 1
  highfreq: 8000
  log: true
  log_zero_guard_type: add
  log_zero_guard_value: 1.0e-05
  lowfreq: 0
  mag_power: 1.0
  n_fft: 1024
  n_window_size: 1024
  n_window_stride: 256
  normalize: null
  pad_to: 1
  pad_value: 0
  preemph: null
  sample_rate: 22050
  window: hann
  window_size: null
  window_stride: null
input_fft:
  _target_: nemo.collections.tts.modules.transformer.FFTransformerEncoder
  n_layer: 6
  n_head: 1
  d_model: 384
  d_head: 64
  d_inner: 1536
  kernel_size: 3
  dropout: 0.1
  dropatt: 0.1
  dropemb: 0.0
  d_embed: 384
output_fft:
  _target_: nemo.collections.tts.modules.transformer.FFTransformerDecoder
  n_layer: 6
  n_head: 1
  d_model: 384
  d_head: 64
  d_inner: 1536
  kernel_size: 3
  dropout: 0.1
  dropatt: 0.1
  dropemb: 0.0
alignment_module:
  _target_: nemo.collections.tts.modules.aligner.AlignmentEncoder
  n_text_channels: 384
duration_predictor:
  _target_: nemo.collections.tts.modules.fastpitch.TemporalPredictor
  input_size: 384
  kernel_size: 3
  filter_size: 256
  dropout: 0.1
  n_layers: 2
pitch_predictor:
  _target_: nemo.collections.tts.modules.fastpitch.TemporalPredictor
  input_size: 384
  kernel_size: 3
  filter_size: 256
  dropout: 0.1
  n_layers: 2
optim:
  name: lamb
  lr: 0.1
  betas:
  - 0.9
  - 0.98
  weight_decay: 1.0e-06
  sched:
    name: NoamAnnealing
    warmup_steps: 1000
    last_epoch: -1
    d_model: 1
target: nemo.collections.tts.models.fastpitch.FastPitchModel
